run:
  timeout: "5m"

linters:
  disable-all: true
  enable: ["revive", "govet", "goimports", "gofmt", "gosec", "staticcheck"]

linters-settings:
  goimports:
    local-prefixes: "https://github.com/appkins-org/terraform-provider-ironic"
  govet:
    check-shadowing: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:"
